"""reduced to one sufficient table

Revision ID: 6f7df9e7c763
Revises: 72834fecd6ef
Create Date: 2021-09-29 21:42:49.524726

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6f7df9e7c763'
down_revision = '72834fecd6ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_discord_data')
    op.drop_table('reminder')
    op.create_table('reminder',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('remind_msg', sa.String(), nullable=True),
                    sa.Column('remind_time', sa.DATETIME(), nullable=True),
                    sa.Column('creation_time', sa.DATETIME(), nullable=True),
                    sa.Column('reminded', sa.Boolean(), nullable=True),
                    sa.Column('author_id', sa.Integer(), nullable=True),
                    sa.Column('channel_id', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminder', sa.Column('discord_data_id', sa.INTEGER(), nullable=True))
    op.drop_column('reminder', 'channel_id')
    op.drop_column('reminder', 'author_id')
    op.create_table('reminder_discord_data',
                    sa.Column('reminder_id', sa.INTEGER(), nullable=False),
                    sa.Column('author_id', sa.INTEGER(), nullable=True),
                    sa.Column('channel_id', sa.INTEGER(), nullable=True),
                    sa.PrimaryKeyConstraint('reminder_id')
                    )
    # ### end Alembic commands ###
